name: CI

on:
  push:
    branches:
      - main

    pull_request:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable pnpm
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: lts/*
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm vitest --coverage
      - uses: codecov/codecov-action@v3
        if: ${{ env.CODECOV_TOKEN != '' }}
        with:
          token: ${{ env.CODECOV_TOKEN }}
